### ISSUE TITLE
symfony/finder version conflict

### ISSUE THREAD

**Issue by Dylan-DutchAndBold** [MegaChriz/afasprofit#1]
Looking at your AFAS client library, it seems to me it's the best option compared to the other available libraries within packagist. However it has a conflict when using symfony/finder of a version above 4.0.0. Is there a reason why it's locked to `">=2.7 <4.0.0"`

**Comment by MegaChriz** [comment]
Thanks for trying out the library!

The main reason is that since I also develop on Drupal, I took over their version constraints for Symfony components. Drupal 8.6 requires Symfony ~3.4.0. Other reason is that I haven't tested this library with Symfony 4.

Let me know if you notice no issues when using this library with Symfony 4, then I'll update the version constraints.

**Comment by Dylan-DutchAndBold** [comment]
Test do seem to run fine with `v4.2.1` `OK (463 tests, 801 assertions)`

**Comment by Dylan-DutchAndBold** [comment]
Tests also seem to run fine with `symfony/dependency-injection` at `v4.2.1`. So this could also be bumped up.

**Comment by Dylan-DutchAndBold** [comment]
I'll make an PR in a sec

**Comment by MegaChriz** [comment]
Note that one dependency - drupal/core-plugin - still requires a Symfony component that is lower than version 4:

`"symfony/validator": ">=2.7 <4.0.0"`
